name = "aoc"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gladvent = ">= 2.2.1 and < 3.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
cell = ">= 1.0.0 and < 2.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
temporary = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
